"""initial schema

Revision ID: 9324116de86b
Revises: 
Create Date: 2026-02-12 12:13:41.810451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9324116de86b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('sales_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_bill_id', sa.String(length=255), nullable=True),
    sa.Column('customer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_documents')),
    sa.UniqueConstraint('external_bill_id', name=op.f('uq_sales_documents_external_bill_id'))
    )
    op.create_index(op.f('ix_sales_documents_id'), 'sales_documents', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('name', name=op.f('uq_warehouses_name'))
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('billing_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=128), nullable=False),
    sa.Column('billing_type', sa.Enum('INCOMING', 'OUTGOING', name='billing_type'), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('customer_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(), nullable=True),
    sa.Column('net_amount', sa.Numeric(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='payment_status'), nullable=True),
    sa.Column('payment_mode', sa.String(length=64), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_file_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_billing_documents_supplier_id_suppliers')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_billing_documents_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_documents')),
    sa.UniqueConstraint('bill_number', name=op.f('uq_billing_documents_bill_number'))
    )
    op.create_index(op.f('ix_billing_documents_id'), 'billing_documents', ['id'], unique=False)
    op.create_table('daily_warehouse_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_incoming', sa.Numeric(), nullable=True),
    sa.Column('total_outgoing', sa.Numeric(), nullable=True),
    sa.Column('expired_stock', sa.Numeric(), nullable=True),
    sa.Column('damaged_stock', sa.Numeric(), nullable=True),
    sa.Column('revenue_generated', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_daily_warehouse_metrics_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_warehouse_metrics'))
    )
    op.create_index('ix_daily_warehouse_date', 'daily_warehouse_metrics', ['warehouse_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_warehouse_metrics_id'), 'daily_warehouse_metrics', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reorder_threshold', sa.Numeric(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_items_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=128), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('expected_delivery', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number'))
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('room_type', sa.Enum('NORMAL', 'COLD_STORAGE', 'PACKING', 'OTHER', name='room_type'), nullable=True),
    sa.Column('temperature_min', sa.Numeric(), nullable=True),
    sa.Column('temperature_max', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_rooms_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('billing_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['billing_documents.id'], name=op.f('fk_billing_lines_bill_id_billing_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_billing_lines_item_id_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_lines'))
    )
    op.create_index(op.f('ix_billing_lines_id'), 'billing_lines', ['id'], unique=False)
    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=255), nullable=True),
    sa.Column('quantity_total', sa.Numeric(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DAMAGED', 'RESERVED', name='batch_status'), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('last_movement_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_inventory_batches_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_inventory_batches_room_id_rooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_batches_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_batches'))
    )
    op.create_index(op.f('ix_inventory_batches_id'), 'inventory_batches', ['id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('qty_ordered', sa.Numeric(), nullable=False),
    sa.Column('qty_received', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('batch_number_suggested', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_po_lines_item_id_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_po_lines_po_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_lines'))
    )
    op.create_index(op.f('ix_po_lines_id'), 'po_lines', ['id'], unique=False)
    op.create_table('sales_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('batch_preferred', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_sales_lines_item_id_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales_documents.id'], name=op.f('fk_sales_lines_sale_id_sales_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_lines'))
    )
    op.create_index(op.f('ix_sales_lines_id'), 'sales_lines', ['id'], unique=False)
    op.create_table('time_series_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty_sold', sa.Numeric(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_time_series_sales_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_time_series_sales_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_series_sales'))
    )
    op.create_index('ix_time_series_item_date', 'time_series_sales', ['item_id', 'date'], unique=False)
    op.create_index(op.f('ix_time_series_sales_id'), 'time_series_sales', ['id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER', name='movement_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tx_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], name=op.f('fk_stock_movements_batch_id_inventory_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_stock_movements_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_stock_movements_room_id_rooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_movements_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_time_series_sales_id'), table_name='time_series_sales')
    op.drop_index('ix_time_series_item_date', table_name='time_series_sales')
    op.drop_table('time_series_sales')
    op.drop_index(op.f('ix_sales_lines_id'), table_name='sales_lines')
    op.drop_table('sales_lines')
    op.drop_index(op.f('ix_po_lines_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_inventory_batches_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index(op.f('ix_billing_lines_id'), table_name='billing_lines')
    op.drop_table('billing_lines')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_daily_warehouse_metrics_id'), table_name='daily_warehouse_metrics')
    op.drop_index('ix_daily_warehouse_date', table_name='daily_warehouse_metrics')
    op.drop_table('daily_warehouse_metrics')
    op.drop_index(op.f('ix_billing_documents_id'), table_name='billing_documents')
    op.drop_table('billing_documents')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_sales_documents_id'), table_name='sales_documents')
    op.drop_table('sales_documents')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
